### ISSUE TITLE
Meet with Environmental Resource Management

### ISSUE THREAD

**Issue by lortrent** [Capital-Regional-District/website#2]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:

Interview key staff to develop an understanding of audences, areas of interest and how they website can address internal business needs.  Also identify existing website content/components for further assessment and replacement.

#Outcome:
- [ ]    03Requirements/... spreadsheet.
- [ ] 
- [ ] 

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]

**Comment by zoekgray** [comment]
Meeting scheduled for late March when ERM team more available.
